#Server Port
server:
  port: 8765

spring:
  application:
    name: zuul-server

#EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
